### ISSUE TITLE
[SonarQube] Security Hotspot - Make sure disabling Spring Security's CSRF protection is safe here.

### ISSUE THREAD

**Issue by AntonNiko** [seng426-team3/vega-spring#80]
![Capture7](https://user-images.githubusercontent.com/18293231/181625899-a9baf682-c1c0-41da-9217-7fe7c5efefb1.PNG)

**Comment by kianapaz** [comment]
The current application uses the JWT Authentication, and JWT tokens. And so the user will be properly authenticated, and will not be able to access other pages without the adequate privileges (role as a user). 
It would be best to enable CSRF, ensuring better security against cross site request forgery. However, CSRF doesn't allow POST requests, which is what the application uses to login. And so, when the CSRf is enabled, it now uses a CSRF token on top of the JWT, and doesn't permit any user to login, not even the admin. 
In this case, the JWT authentication will work, but it would be advised in the future to enable CSRF, and add a CSRF token along with the JWT token. 

Closing this ticket because I couldn't find an adequate fix for the given time.
